### ISSUE TITLE
Triggered Send Failing.

### ISSUE THREAD

**Issue by iCreateJB** [salesforce-marketingcloud/FuelSDK-Ruby#19]
Triggered Sends are failing when I use the gem. 

I have checked against another gem 'exact_target' and the credentials are valid as the calls go through but I actually get a describe error when trying to perform the same action using this gem. 

[ Sensitive information such a keys and email addresses have been filtered out ]

auth = FuelSDK::Client.new({'client'=>{'id'=>'#{ENV['client_id']}','secret'=>'#{ENV['client_secret']}'}})
 => #<FuelSDK::Client:0x007fb58bbff4d0 @debug=false, @id="#{ENV['client_id']}", @secret="#{ENV['client_secret']}", @signature=nil> 
1.9.3p484 :035 > auth.debug = true
 => true 
1.9.3p484 :036 > ts = FuelSDK::TriggeredSend.new
 => #<FuelSDK::TriggeredSend:0x007fb58bc42708> 
1.9.3p484 :037 > ts.authStub = auth
 => #<FuelSDK::Client:0x007fb58bbff4d0 @debug=true, @id="#{ENV['client_id']}", @secret="#{ENV['client_secret']}", @signature=nil> 
1.9.3p484 :038 > ts.props = { "CustomerKey" => "Test" }
 => {"CustomerKey"=>"Test"} 
1.9.3p484 :039 > ts.subscribers = [{"EmailAddress"=>"test.user@company.com","SubscriberKey"=>"test.user@company.com"}]
 => [{"EmailAddress"=>"test.user@company.com", "SubscriberKey"=>"test.user@company.com"}] 
1.9.3p484 :040 > rs = ts.send

FuelSDK::DescribeError: Unable to get TriggeredSend
	from ~/.rvm/gems/ruby-1.9.3-p484@journey-merchant-portal/gems/fuelsdk-0.1.6/lib/fuelsdk/soap.rb:163:in `get_all_object_properties'
	from ~/.rvm/gems/ruby-1.9.3-p484@journey-merchant-portal/gems/fuelsdk-0.1.6/lib/fuelsdk/soap.rb:213:in `get_editable_properties'
	from ~/.rvm/gems/ruby-1.9.3-p484@journey-merchant-portal/gems/fuelsdk-0.1.6/lib/fuelsdk/soap.rb:356:in `format_object_cud_properties'
	from ~/.rvm/gems/ruby-1.9.3-p484@journey-merchant-portal/gems/fuelsdk-0.1.6/lib/fuelsdk/soap.rb:377:in `normalize_properties_for_cud'
	from ~/.rvm/gems/ruby-1.9.3-p484@journey-merchant-portal/gems/fuelsdk-0.1.6/lib/fuelsdk/soap.rb:385:in `soap_cud'
	from ~/.rvm/gems/ruby-1.9.3-p484@journey-merchant-portal/gems/fuelsdk-0.1.6/lib/fuelsdk/soap.rb:290:in `soap_post'
	from ~/.rvm/gems/ruby-1.9.3-p484@journey-merchant-portal/gems/fuelsdk-0.1.6/lib/fuelsdk/objects.rb:139:in `send'
	from (irb):40
	from ~/.rvm/gems/ruby-1.9.3-p484@journey-merchant-portal/gems/railties-3.2.16/lib/rails/commands/console.rb:47:in `start'
	from ~/.rvm/gems/ruby-1.9.3-p484@journey-merchant-portal/gems/railties-3.2.16/lib/rails/commands/console.rb:8:in `start'
	from ~/.rvm/gems/ruby-1.9.3-p484@journey-merchant-portal/gems/railties-3.2.16/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

**Comment by michaelstalker** [comment]
@alssndro Did you find a solution to this, or did you just bypass the gem?

**Comment by paulhenrich** [comment]
I had this exact same experience using the packaged Gem from rubygems. I was able to resolve this by switching to using git/master in my Gemfile. It looks like the API for TriggeredSend changed recently judging by the documentation change here: https://github.com/ExactTarget/FuelSDK-Ruby/commit/431be45215573f7f4ae8926b80f2ef4ba953da2a
