### ISSUE TITLE
Data Extension - Remove Row

### ISSUE THREAD

**Issue by raphaelp** [salesforce-marketingcloud/FuelSDK-Ruby#23]
I'm using the fuelsdk gem and when I try to remove a data extension row I'm having a problem.

This is my code:

client = ET_Client.new auth

de_row = ET_DataExtension::Row.new()
de_row.authStub = client
de_row.CustomerKey = "XXXXXXXXXXXX"
de_row.props = {"Web_FIC" => fic}
response = de_row.delete

This is my error

TypeError: can't convert String into Integer
from /Users/raphaelpetegrosso/.rvm/gems/ruby-1.9.3-p484/gems/fuelsdk-0.1.7/lib/fuelsdk/objects.rb:220:in `[]='
from /Users/raphaelpetegrosso/.rvm/gems/ruby-1.9.3-p484/gems/fuelsdk-0.1.7/lib/fuelsdk/objects.rb:220:in`block in add_customer_key'
from /Users/raphaelpetegrosso/.rvm/gems/ruby-1.9.3-p484/gems/fuelsdk-0.1.7/lib/fuelsdk/objects.rb:218:in `each'
from /Users/raphaelpetegrosso/.rvm/gems/ruby-1.9.3-p484/gems/fuelsdk-0.1.7/lib/fuelsdk/objects.rb:218:in`add_customer_key'
from /Users/raphaelpetegrosso/.rvm/gems/ruby-1.9.3-p484/gems/fuelsdk-0.1.7/lib/fuelsdk/objects.rb:212:in `delete'
from (irb):37
from /Users/raphaelpetegrosso/.rvm/gems/ruby-1.9.3-p484/gems/railties-3.2.17/lib/rails/commands/console.rb:47:in`start'
from /Users/raphaelpetegrosso/.rvm/gems/ruby-1.9.3-p484/gems/railties-3.2.17/lib/rails/commands/console.rb:8:in `start'
from /Users/raphaelpetegrosso/.rvm/gems/ruby-1.9.3-p484/gems/railties-3.2.17/lib/rails/commands.rb:41:in`<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in`<main>'

So I opened your gem and checked that the error was in this line:

d['CustomerKey'] = customer_key

but in my case d is an array and not a hash. Then I changed the code to this:
d << 'CustomerKey'
d <<  customer_key

And it worked, but my response came with this error:

status_message=>"Exception occurred during [Delete] ErrorID: 1913074240"

It seems that the gem version is not updated, right? Any idea what is the error?

Thanks

**Comment by jwrobes** [comment]
I figured this out.  The documentation on this [page](https://code.exacttarget.com/apis-sdks/fuel-sdks/data-extension-rows/data-extension-row-create.html) is incorrect.  

You need to wrap the properties hash in an array.  And then it will work.
You can create multiple rows at once by adding multiple hashes into the array.  So this:

dataextensionrow.props = {"Name" => "ExampleNameValue", "OtherField" => "Some randon text for the other field"}

Should be this:
dataextensionrow.props = [{"Name" => "ExampleNameValue", "OtherField" => "Some randon text for the other field"}]
