### ISSUE TITLE
Additional maintainer?

### ISSUE THREAD

**Issue by will-in-wi** [salesforce-marketingcloud/FuelSDK-Ruby#78]
My company is switching to MarketingCloud and we are heavily depending on this SDK. I'd like to help maintain this gem, set up automated tests, and clean up the issue and PR queues. I am presently one of the maintainers of Capistrano, and have a number of years of experience maintaining Ruby applications.

Would any of the maintainers be willing to bring me on board with this?

Thanks!
~William Johnston
Software Engineer
Minnesota Public Radio/American Public Media

cc: @barberj (it looks like you've been doing work most recently, thanks!)

**Comment by barberj** [comment]
@will-in-wi I don't have any permissions in the salesforce-marketingcloud organization. Sorry

**Comment by wrs** [comment]
One year later… We are also trying to bring up MarketingCloud and trying to decide whether to use this SDK, which seems to be abandoned. @amagar088, you did the last string of commits (ending in 2016) — are you still around? What is the plan here?

@will-in-wi and @barberj are you still involved with this code? Should we consider joining forces with like-minded customers and moving the center of gravity to another fork? There are a bunch of forks and a lot of them have useful looking tweaks and more major things like Savon compatibility fixes.

**Comment by will-in-wi** [comment]
@wrs I've since changed jobs and no longer work with this gem. I'd be interested in helping maintain something, except that I now work for a competitor of marketing cloud. :)
