### ISSUE TITLE
Please deprecate this repository

### ISSUE THREAD

**Issue by hendricius** [salesforce-marketingcloud/FuelSDK-Ruby#93]
Please deprecate this repository, or give a full revamp.

Being a developer it's not pleasant at all to work with this code. Many common practices have not been followed. I've spent so much time already trying to debug this.

**Comment by manivinesh** [comment]
@hendricius Apologies for the inconvenience. We have to admit that the Marketing Cloud SDK's weren't maintained well. But we have already started the planning for revamping all our SDKs. We will soon create Milestones to revamp the code and also address all the issues. We are establishing all the process needed to change these SDKs into a well maintained code.

**Comment by hendricius** [comment]
That would be amazing! Thank you.
